resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/joelbinn/concourse-maven-proj.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s

jobs:
- name: build
  plan:
  - get: every-1m
    trigger: true
  - task: maven
    config:
      platform: linux
      image_resource:
        source:
          repository: java
          tag: '8'
        run:
          path: ./mvnw
          args: ["-v"]
