resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/joelbinn/concourse-maven-proj.git
      branch: master

jobs:
- name: build
  plan:
  - aggregate:
    - get: source-code
      trigger: true
  - task: maven-version-12
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      inputs:
        - name: source-code
      run:
        #path: echo
        #args: ["hej"]
        #path: ./mvnw
        #args: [-v]
        path: source-code/build.sh
        args: ['source-code']
